--fix action bar
MainMenuBar:EnableMouse(false)
MainMenuBarArtFrame:EnableMouse(false)
MainMenuBarLeftEndCap:Hide()
MainMenuBarRightEndCap:Hide()
MainMenuBarTexture0:Hide()
MainMenuBarTexture1:Hide()
MainMenuBarTexture2:Hide()
MainMenuBarTexture3:Hide()
MainMenuMaxLevelBar0:Hide()
MainMenuMaxLevelBar1:Hide()
MainMenuMaxLevelBar2:Hide()
MainMenuMaxLevelBar3:Hide()
StanceBarLeft:SetAlpha(0)
StanceBarMiddle:SetAlpha(0)
StanceBarRight:SetAlpha(0)
SlidingActionBarTexture0:SetAlpha(0)
SlidingActionBarTexture1:SetAlpha(0)
ExhaustionLevelFillBar:Hide()
MainMenuXPBarTexture0:Hide()
MainMenuXPBarTexture1:Hide()
MainMenuXPBarTexture2:Hide()
MainMenuXPBarTexture3:Hide()
MainMenuBarMaxLevelBar:Hide()
MainMenuMaxLevelBar0:Hide()
MainMenuMaxLevelBar1:Hide()
MainMenuMaxLevelBar2:Hide()
MainMenuMaxLevelBar3:Hide()
ReputationWatchBar.StatusBar.XPBarTexture0:Hide()
ReputationWatchBar.StatusBar.XPBarTexture1:Hide()
ReputationWatchBar.StatusBar.XPBarTexture2:Hide()
ReputationWatchBar.StatusBar.XPBarTexture3:Hide()
ReputationWatchBar.StatusBar.WatchBarTexture0:Hide()
ReputationWatchBar.StatusBar.WatchBarTexture1:Hide()
ReputationWatchBar.StatusBar.WatchBarTexture2:Hide()
ReputationWatchBar.StatusBar.WatchBarTexture3:Hide()
-- hide backpack
MainMenuBarBackpackButton:Hide()
CharacterBag0Slot:Hide()
CharacterBag1Slot:Hide()
CharacterBag2Slot:Hide()
CharacterBag3Slot:Hide()
-- hide micro menu
CharacterMicroButton:Hide()
SpellbookMicroButton:Hide()
TalentMicroButton:SetScale(0.0001)
TalentMicroButton:EnableMouse(false)
QuestLogMicroButton:Hide()
WorldMapMicroButton:Hide()
SocialsMicroButton:Hide()
HelpMicroButton:Hide()
MainMenuMicroButton:Hide()
MainMenuBarPageNumber:Hide()
KeyRingButton:SetAlpha(0)
MainMenuBarPerformanceBar:SetAlpha(0)
MainMenuBarPerformanceBar:Hide()
ActionBarDownButton:Hide()
ActionBarUpButton:Hide()
-- action bar location
MainMenuBar:SetScale(0.8)
MainMenuBar:ClearAllPoints()
MainMenuBar:SetPoint('BOTTOM', UIParent, 293, 0)
--pet bar
PetActionBarFrame:SetScale(0.8)
PetActionBarFrame:ClearAllPoints()
PetActionBarFrame:SetPoint('BOTTOM', UIParent, 380, 475)